### ISSUE TITLE
Can we make options to limit memory and CPU usage?

### ISSUE THREAD

**Issue by Riku32** [dop251/goja#196] opened 2020-09-05 22:00 UTC
I want to be able to limit memory and CPU usage per runtime. This would be useful for user-created scripts and custom functionality. Like let's say a discord bot that can run custom commands, you don't want people to be able to exhaust the CPU or memory.

**Comment by dop251** [comment] 2020-09-06 10:34
Duplicate of #6

**Closed by dop251** 2020-09-06 10:34 UTC
